### ISSUE TITLE
path prefix may be "file:" instead of "file://"

### ISSUE THREAD

**Issue by szkrd** [larspontoppidan/clipboard-files#2]
It seems to me that when I copy a file in _WebStorm_ then the prefix is slightly different from the expected `file://`

**Comment by larspontoppidan** [comment]
Hi szkrd, thanks for the issue and pull request. I made a modification to your fix so regular `file://` prefix still works.

Could you check that the issue is solved now?

**Comment by szkrd** [comment]
Yes, it's working fine! Thanks!
